services:
  subquery-node:
    image: subquerynetwork/subql-node-stellar:latest
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      DB_USER: postgres
      DB_PASS: rUoedpmygVqGSBbWOWTlueptlZcjAyqp
      DB_DATABASE: railway
      DB_HOST: trolley.proxy.rlwy.net
      DB_PORT: 50588
    volumes:
      - ./:/app
    command:
      - ${SUB_COMMAND:-} # set SUB_COMMAND env variable to "test" to run tests
      - -f=/app
      - --db-schema=public
      - --workers=5 # Ultra conservative - single worker to avoid rate limits
      - --batch-size=10 # Process one ledger at a time
      - --unsafe
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/ready"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - subquery

  # graphql-engine:
  #   image: subquerynetwork/subql-query:latest
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     subquery-node:
  #       condition: service_healthy
  #   restart: always
  #   environment:
  #     DB_USER: postgres
  #     DB_PASS: rUoedpmygVqGSBbWOWTlueptlZcjAyqp
  #     DB_DATABASE: railway
  #     DB_HOST: trolley.proxy.rlwy.net
  #     DB_PORT: 50588
  #   command:
  #     - --name=app
  #     - --playground
  #     - --indexer=http://subquery-node:3000
  #     - --cors=*
  #   networks:
  #     - subquery

networks:
  subquery:
    driver: bridge
